name: dvbfixer
channels:
  - conda-forge
  - salilab
dependencies:
  - python >=3.11
  - numpy
  - scipy
  - openmm >=8.1
  - pdbfixer >=1.9
  - openmmforcefields
  - openff-toolkit
  - rdkit
  - biopython
  - modeller
  - parmed
  - pip
  - pip:
    - propka >=3.5
    - acpype
