name: dvbfixer-rfdiffusion-v1
channels:
  - nvidia
  - dglteam
  - conda-forge
dependencies:
  - python=3.9.19
  - cudatoolkit=11.1.74
  - dgl-cuda11.1=0.9.1post1
  - hydra-core=1.3.2
  - icecream=2.1.6
  - numpy=1.26.4
  - pip=25.2
  - pyrsistent=0.20.0
  - scipy=1.13.1
  - pip:
      - --find-links=https://download.pytorch.org/whl/torch_stable.html
      - torch==1.9.0+cu111
      - torchvision==0.10.0+cu111
      - torchaudio==0.9.0
      - decorator==5.1.0
      - e3nn==0.3.3
      - pynvml==11.0.0
      - wandb==0.12.0
      - git+https://github.com/NVIDIA/dllogger.git@0478734ff7be75adde8d160e04872664d1c62e5f
