"""GROMACS topology + PDB output writers for ``dvbfixer top``.

Split out of the flat ``top.py`` in the Phase 2.4 follow-up work.
Owns everything that writes a file — moleculetype sections, .top /
.pdb / posre.itp emitters, FF-content splicing, water and ion topology
emission.

The writers take already-built ``ChainTopology`` / ``AtomEntry`` /
``PDBResidue`` instances via parameters and duck-type through them —
so no dataclass imports back into pipeline.
"""

from __future__ import annotations

from pathlib import Path

from dvbfixer.top.ff_data import (
    _GLYCAN_LINKAGE_PARAMS,
    _ION_ATOMTYPE_NAMES,
    ION_PARAMS,
)


# ---------------------------------------------------------------------------
# Writers
# ---------------------------------------------------------------------------
def _write_moleculetype(f, chain_top, bonded_types):
    """Write a chain moleculetype section to an open file handle."""
    bt = bonded_types

    # [ moleculetype ]
    f.write("[ moleculetype ]\n")
    f.write("; Name            nrexcl\n")
    f.write(f"{chain_top.name:<18s}{chain_top.nrexcl}\n\n")

    # [ atoms ]
    f.write("[ atoms ]\n")
    f.write(";   nr       type  resnr residue  atom   cgnr     charge       mass\n")
    for a in chain_top.atoms:
        f.write(f"{a.index:6d} {a.atom_type:>10s} {a.resnr:6d} {a.resname:>6s} "
                f"{a.atomname:>6s} {a.cgnr:6d} {a.charge:11.4f} {a.mass:11.4f}\n")
    f.write("\n")

    # [ bonds ]
    if chain_top.bonds:
        f.write("[ bonds ]\n")
        f.write(";  ai    aj funct\n")
        for i, j in chain_top.bonds:
            f.write(f"{i:5d} {j:5d} {bt.bond_type:5d}\n")
        f.write("\n")

    # [ pairs ]
    if chain_top.pairs:
        f.write("[ pairs ]\n")
        f.write(";  ai    aj funct\n")
        for i, j in chain_top.pairs:
            f.write(f"{i:5d} {j:5d}     1\n")
        f.write("\n")

    # [ angles ]
    if chain_top.angles:
        f.write("[ angles ]\n")
        f.write(";  ai    aj    ak funct\n")
        for angle in chain_top.angles:
            if len(angle) == 4:
                i, j, k, ftype = angle
                f.write(f"{i:5d} {j:5d} {k:5d} {ftype:5d}\n")
            else:
                i, j, k = angle
                f.write(f"{i:5d} {j:5d} {k:5d} {bt.angle_type:5d}\n")
        f.write("\n")

    # [ dihedrals ] — proper
    if chain_top.dihedrals:
        f.write("[ dihedrals ]\n")
        f.write(";  ai    aj    ak    al funct\n")
        for dih in chain_top.dihedrals:
            if len(dih) == 5:
                # Named dihedral type (AMBER ILDN)
                i, j, k, l, dtype = dih
                f.write(f"{i:5d} {j:5d} {k:5d} {l:5d} {bt.dihedral_type:5d}  ; {dtype}\n")
            else:
                i, j, k, l = dih
                f.write(f"{i:5d} {j:5d} {k:5d} {l:5d} {bt.dihedral_type:5d}\n")
        f.write("\n")

    # [ dihedrals ] — improper
    if chain_top.impropers:
        f.write("[ dihedrals ] ; impropers\n")
        f.write(";  ai    aj    ak    al funct\n")
        for i, j, k, l in chain_top.impropers:
            f.write(f"{i:5d} {j:5d} {k:5d} {l:5d} {bt.improper_type:5d}\n")
        f.write("\n")

    # [ cmap ]
    if chain_top.cmap:
        f.write("[ cmap ]\n")
        f.write(";  ai    aj    ak    al    am funct\n")
        for i, j, k, l, m in chain_top.cmap:
            f.write(f"{i:5d} {j:5d} {k:5d} {l:5d} {m:5d}     1\n")
        f.write("\n")

    # Position restraints include (stays as separate file with #ifdef)
    posre_name = f"posre_{chain_top.name}.itp"
    f.write("; Include Position restraint file\n")
    f.write("#ifdef POSRES\n")
    f.write(f'#include "{posre_name}"\n')
    f.write("#endif\n\n")


def write_pdb(chain_tops, path, extra_pdb_lines=None, cryst1=None):
    """Write a PDB file with atom names matching the topology.

    extra_pdb_lines: list of raw PDB ATOM/HETATM lines to append
    (for ions/BUF particles not built as chain topologies).
    """
    serial = 0
    with open(path, 'w') as f:
        f.write("REMARK    Generated by dvbfixer top\n")
        if cryst1:
            f.write(cryst1 if cryst1.endswith('\n') else cryst1 + '\n')
        for ct in chain_tops:
            for atom in ct.atoms:
                serial += 1
                # PDB columns: 13-16 atom name, 17 altLoc, 18-20 resName
                name = atom.atomname
                if len(name) < 4:
                    name_field = f" {name:<3s}"
                else:
                    name_field = f"{name:<4s}"

                # Determine element from atom name
                elem = name[0] if name[0].isalpha() else name[1]

                # Use orig_resname (PDB name, includes protonation renames)
                # atom.resname is the RTP name (e.g. BGLCNA for glycans)
                resname = atom.orig_resname
                # PDB cols: 17=altLoc, 18-20=resName, 21=space, 22=chainID
                # 4-char resnames (ASPP, GLUP): cols 18-21, no space before chainID
                if len(resname) <= 3:
                    res_chain = f" {resname:>3s} {atom.chain_id}"  # " ASP A"
                else:
                    res_chain = f" {resname:<4s}{atom.chain_id}"   # " ASPP A" (no gap)

                f.write(
                    f"ATOM  {serial % 100000:5d} {name_field}"
                    f"{res_chain}"
                    f"{atom.orig_resseq:4d}"
                    f"    "
                    f"{atom.x:8.3f}{atom.y:8.3f}{atom.z:8.3f}"
                    f"  1.00  0.00"
                    f"          "
                    f"{elem:>2s}\n"
                )
            # TER record after each chain
            if ct.atoms:
                last = ct.atoms[-1]
                serial += 1
                resname = last.orig_resname
                if len(resname) <= 3:
                    res_chain = f" {resname:>3s} {last.chain_id}"
                else:
                    res_chain = f" {resname:<4s}{last.chain_id}"
                f.write(
                    f"TER   {serial % 100000:5d}      "
                    f"{res_chain}"
                    f"{last.orig_resseq:4d}\n"
                )
        # Append extra molecules (ions/water/small molecules) with renumbered serials
        if extra_pdb_lines:
            resseq = 0
            prev_resid = None
            for line in extra_pdb_lines:
                serial += 1
                # Track residue changes for resseq renumbering
                orig_resid = line[17:26]  # resname + chain + resseq
                if orig_resid != prev_resid:
                    resseq += 1
                    prev_resid = orig_resid
                # Rewrite serial (cols 7-11), clear chain ID (col 22),
                # and renumber resseq (cols 23-26)
                f.write(f"{line[:6]}{serial % 100000:5d}{line[11:21]} "
                        f"{resseq % 10000:4d}{line[26:]}")
        f.write("END\n")


def write_posre(chain_top, path, fc=1000.0):
    """Write position restraint file for heavy atoms."""
    with open(path, 'w') as f:
        f.write("; Position restraints for heavy atoms\n")
        f.write("; Generated by dvbfixer top\n\n")
        f.write("[ position_restraints ]\n")
        f.write(";  ai  funct    fcx      fcy      fcz\n")
        for atom in chain_top.atoms:
            # Restrain heavy atoms only (not hydrogen)
            if not atom.atomname.startswith('H') and atom.atomname not in ('HN',):
                f.write(f"{atom.index:5d}     1  {fc:.1f}  {fc:.1f}  {fc:.1f}\n")


def _read_ff_content(path, keep_posres_ifdef=False):
    """Read a force field file, stripping preprocessor directives.

    Removes #include, #define, #ifdef, #ifndef, #else, #endif lines
    so the content can be inlined directly into the .top file.

    If keep_posres_ifdef=True, preserves #ifdef POSRES_* blocks
    (used for ions.itp which may have position restraint sections).
    """
    lines = []
    in_posres_ifdef = False
    with open(path) as f:
        for line in f:
            stripped = line.strip()
            if keep_posres_ifdef:
                if stripped.startswith('#ifdef POSRES'):
                    in_posres_ifdef = True
                    lines.append(line)
                    continue
                if in_posres_ifdef and stripped == '#endif':
                    in_posres_ifdef = False
                    lines.append(line)
                    continue
                if in_posres_ifdef:
                    lines.append(line)
                    continue
            if stripped.startswith(('#include', '#define', '#ifdef', '#ifndef',
                                    '#else', '#endif', '#error')):
                continue
            lines.append(line)
    return ''.join(lines)


def _parse_defaults(ff_dir):
    """Extract [ defaults ] section from forcefield.itp."""
    ff_itp = ff_dir / 'forcefield.itp'
    in_defaults = False
    defaults_lines = []
    with open(ff_itp) as f:
        for line in f:
            stripped = line.strip()
            if stripped.startswith('[ defaults ]'):
                in_defaults = True
                defaults_lines.append(line)
                continue
            if in_defaults:
                if stripped.startswith('[') or stripped.startswith('#include'):
                    break
                defaults_lines.append(line)
    return ''.join(defaults_lines)


def _dedup_atomtypes(content):
    """Remove duplicate atomtype entries, keeping the last definition.

    CHARMM ffnonbonded.itp has duplicate entries (e.g. HT, OT) from
    #ifdef HEAVY_H blocks — one with heavy mass, one with real mass.
    After stripping preprocessor directives, both remain. We keep the
    last definition for each atomtype name.
    """
    lines = content.split('\n')
    in_atomtypes = False
    atomtype_lines = []   # (line_idx, atomtype_name, line)
    other_lines = []      # (line_idx, line)

    for idx, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith('[ atomtypes ]'):
            in_atomtypes = True
            other_lines.append((idx, line))
            continue
        if in_atomtypes and stripped.startswith('['):
            in_atomtypes = False
            other_lines.append((idx, line))
            continue
        if in_atomtypes and stripped and not stripped.startswith(';'):
            parts = stripped.split()
            if parts:
                atomtype_lines.append((idx, parts[0], line))
            continue
        other_lines.append((idx, line))

    # Keep only last occurrence of each atomtype
    seen = {}
    for idx, name, line in atomtype_lines:
        seen[name] = (idx, line)

    # Reconstruct
    all_entries = other_lines + [(idx, line) for idx, line in seen.values()]
    all_entries.sort(key=lambda x: x[0])
    return '\n'.join(line for _, line in all_entries)


# Extra bonded parameters for CHARMM glycosidic linkage sites.
# When OC311->OC3C61 at linkages, some atom type combos (CC321-OC3C61,
# CC3161-OC3C61-CC3162, etc.) are not in the standard FF distribution.
# Parameters by analogy with existing CC321D/CC321C/CC311D variants.


def _strip_ion_atomtypes(nb_content):
    """Remove ion atom-type lines from ffnonbonded.itp content.

    Lines matched by atom-type name in column 1 against _ION_ATOMTYPE_NAMES.
    Used so the water-matched ion set can replace them.
    """
    lines = nb_content.split('\n')
    kept = []
    for line in lines:
        s = line.strip()
        if not s or s.startswith(';') or s.startswith('['):
            kept.append(line)
            continue
        first = s.split()[0]
        if first in _ION_ATOMTYPE_NAMES:
            continue
        kept.append(line)
    return '\n'.join(kept)


def _emit_ion_atomtypes(ion_set):
    """Return [ atomtypes ]-formatted lines for the chosen ion parameter set."""
    if ion_set not in ION_PARAMS:
        return ''
    table = ION_PARAMS[ion_set]
    lines = [f"; Ion atom types: {ion_set}"]
    for atname, (atnum, mass, sigma, eps, _q, _rn) in table.items():
        lines.append(f"{atname:<8s} {atnum:>5d}  {mass:>9.4f}   0.0000  A "
                     f"  {sigma:.5e}  {eps:.5e}")
    return '\n'.join(lines) + '\n'


def _emit_ions_itp(ion_set, out_path):
    """Write a fresh ions.itp with moleculetypes referencing the ion-set's atom types."""
    if ion_set not in ION_PARAMS:
        # No ion set known — emit empty file with a comment.
        with open(out_path, 'w') as f:
            f.write(f"; No ion parameter set selected (ion_set={ion_set})\n")
        return
    table = ION_PARAMS[ion_set]
    with open(out_path, 'w') as f:
        f.write("; Ion moleculetypes — generated by dvbfixer top\n")
        f.write(f"; Ion parameter set: {ion_set}\n\n")
        for atname, (_atnum, _mass, _sigma, _eps, charge, resname) in table.items():
            f.write("[ moleculetype ]\n")
            f.write("; molname       nrexcl\n")
            f.write(f"{resname:<14s}  1\n\n")
            f.write("[ atoms ]\n")
            f.write("; id    at type         res nr  residu name     at name  cg nr  charge\n")
            f.write(f"1       {atname:<14s}  1       {resname:<14s}  {resname:<6s}  1      {charge:>.5f}\n\n\n")


def write_top(chain_tops, path, ff_dir, ff_type, bonded_types_list,
              water_model='tip3p', system_name='Protein',
              has_interchain_ss=False, extra_molecules=None,
              small_mol_itps=None, ion_set=None):
    """Write topology: FF params in ffparams.itp, rest in topol.top.

    extra_molecules: list of (name, count) for ions/BUF/small molecules/water.
    small_mol_itps: list of small molecule .itp filenames to include.
    ion_set: ion LJ parameter set key (one of ION_PARAMS keys, or None to keep
             the bundled FF ions verbatim — used for CHARMM).
    """
    ff_dir = Path(ff_dir)
    ff_name = ff_dir.name
    out_dir = Path(path).parent

    water_files = {
        'tip3p': 'tip3p.itp',
        'spc': 'spc.itp',
        'spce': 'spce.itp',
        'tip4p': 'tip4p.itp',
        'tip4pew': 'tip4pew.itp',
        'opc': 'opc.itp',
    }

    # --- Write ffparams.itp with all FF parameters ---
    ffparams_path = out_dir / 'ffparams.itp'
    with open(ffparams_path, 'w') as f:
        f.write("; Force field parameters — generated by dvbfixer top\n")
        f.write(f"; Force field: {ff_name}\n\n")

        # [ defaults ]
        f.write(_parse_defaults(ff_dir))
        f.write("\n")

        # [ atomtypes ] from ffnonbonded.itp (deduplicated)
        f.write("; Non-bonded parameters (from ffnonbonded.itp)\n")
        nb_content = _read_ff_content(ff_dir / 'ffnonbonded.itp')
        if ion_set is not None:
            # Replace bundled ion atom types with the water-matched set
            nb_content = _strip_ion_atomtypes(nb_content)
        f.write(_dedup_atomtypes(nb_content))
        if ion_set is not None:
            f.write(_emit_ion_atomtypes(ion_set))
        f.write("\n")

        # [ bondtypes ], [ angletypes ], [ dihedraltypes ] from ffbonded.itp
        f.write("; Bonded parameters (from ffbonded.itp)\n")
        f.write(_read_ff_content(ff_dir / 'ffbonded.itp'))
        f.write("\n")

        # CHARMM extras: cmap.itp, nbfix.itp
        if ff_type == 'charmm':
            cmap_path = ff_dir / 'cmap.itp'
            if cmap_path.exists():
                f.write("; CMAP parameters (from cmap.itp)\n")
                f.write(_read_ff_content(cmap_path))
                f.write("\n")

            nbfix_path = ff_dir / 'nbfix.itp'
            if nbfix_path.exists():
                f.write("; NBFIX parameters (from nbfix.itp)\n")
                f.write(_read_ff_content(nbfix_path))
                f.write("\n")

            # Extra parameters for glycosidic linkage sites.
            # At linkage sites OC311->OC3C61, creating atom type combos
            # not in the standard FF. Parameters by analogy with existing
            # glycosidic linkage params (CC321D/CC311D/CC321C variants).
            f.write(_GLYCAN_LINKAGE_PARAMS)

    # --- Write topol.top ---
    with open(path, 'w') as f:
        f.write("; Generated by dvbfixer top\n")
        f.write(f"; Force field: {ff_name}\n")
        f.write(f"; Water model: {water_model}\n")
        doc_path = ff_dir / 'forcefield.doc'
        if doc_path.exists():
            with open(doc_path) as doc:
                for doc_line in doc:
                    doc_line = doc_line.strip()
                    if doc_line and not all(c == '*' for c in doc_line):
                        f.write(f"; {doc_line}\n")
                        break
        f.write("\n")

        # Include FF parameters
        f.write('#include "ffparams.itp"\n\n')

        # Chain moleculetypes (separate .itp files)
        for ct, bt in zip(chain_tops, bonded_types_list):
            chain_itp = out_dir / f"{ct.name}.itp"
            with open(chain_itp, 'w') as cf:
                cf.write(f"; Moleculetype: {ct.name}\n")
                cf.write("; Generated by dvbfixer top\n\n")
                _write_moleculetype(cf, ct, bt)
            f.write(f'#include "{ct.name}.itp"\n')

        # Small molecule .itp includes (ACET, ACEH, etc.)
        if small_mol_itps:
            for mol_name in small_mol_itps:
                f.write(f'#include "{mol_name}.itp"\n')

        f.write("\n")

        # Water moleculetype (separate .itp)
        water_itp = water_files.get(water_model, 'tip3p.itp')
        water_src = ff_dir / water_itp
        if water_src.exists():
            water_out = out_dir / 'water.itp'
            with open(water_out, 'w') as wf:
                wf.write("; Water topology\n")
                wf.write("; Generated by dvbfixer top\n\n")
                _write_water_topology(wf, water_src)
            f.write('#include "water.itp"\n')

        # Ion moleculetypes (separate .itp)
        ions_out = out_dir / 'ions.itp'
        if ion_set is not None:
            # AMBER path: emit fresh ions.itp matched to the chosen ion set.
            _emit_ions_itp(ion_set, ions_out)
            f.write('#include "ions.itp"\n')
        else:
            # CHARMM path: copy bundled ions.itp verbatim.
            ions_path = ff_dir / 'ions.itp'
            if ions_path.exists():
                with open(ions_out, 'w') as ionf:
                    ionf.write("; Ion topology\n")
                    ionf.write("; Generated by dvbfixer top\n\n")
                    ionf.write(_read_ff_content(ions_path, keep_posres_ifdef=True))
                f.write('#include "ions.itp"\n')
        f.write("\n")

        # [ system ]
        f.write("[ system ]\n")
        f.write("; Name\n")
        f.write(f"{system_name}\n\n")

        # [ molecules ]
        f.write("[ molecules ]\n")
        f.write("; Compound        #mols\n")
        for ct in chain_tops:
            f.write(f"{ct.name:<18s}1\n")
        if extra_molecules:
            for mol_name, mol_count in extra_molecules:
                f.write(f"{mol_name:<18s}{mol_count}\n")

        # Inter-chain SS bonds (must come after [ molecules ])
        if has_interchain_ss:
            f.write('\n; WARNING: The interchain_ss.itp include MUST remain at the end of this file,\n')
            f.write('; after [ molecules ] and after any SOL/ion entries added by gmx solvate/genion.\n')
            f.write('; If you add solvent, move this line below the SOL and ion molecule entries.\n')
            f.write('#include "interchain_ss.itp"\n')


def _write_water_topology(f, water_path):
    """Write water moleculetype from .itp file, using rigid (settles) version.

    Water .itp files have #ifndef FLEXIBLE / #else blocks. We extract only
    the rigid (settles) section since that's the standard for MD.
    """
    lines = []
    in_flexible = False
    skip_block = False

    with open(water_path) as wf:
        for line in wf:
            stripped = line.strip()

            # Track preprocessor blocks
            if stripped == '#ifndef FLEXIBLE' or stripped == '#ifdef FLEXIBLE':
                # #ifndef FLEXIBLE → rigid section follows (keep it)
                # #ifdef FLEXIBLE → flexible section follows (skip it)
                in_flexible = stripped == '#ifdef FLEXIBLE'
                skip_block = in_flexible
                continue
            elif stripped == '#else':
                # Toggle: if we were in rigid, now flexible (skip); vice versa
                skip_block = not skip_block
                continue
            elif stripped == '#endif':
                skip_block = False
                in_flexible = False
                continue
            elif stripped.startswith('#'):
                continue

            if not skip_block:
                lines.append(line)

    f.write(''.join(lines))


