#!/usr/bin/env python
"""Generate ``docs/reference/{cmd}.md`` from each subcommand's argparse.

Every subcommand module in ``src/dvbfixer/`` exposes a ``parse_args``
function that builds an ``argparse.ArgumentParser``. This script imports
each ``parse_args``, calls the parser's ``format_help()`` (via a
programmatic ``--help`` invocation caught through ``SystemExit``), and
writes the resulting text into a Markdown page.

Modes
-----

- Default (no flag) — write / overwrite the reference tree.
- ``--check`` — assemble the pages in memory and diff them against the
  committed tree. Prints a summary of drifted files and exits 1 when
  anything differs. Used by CI to enforce that the reference tree
  matches the current ``--help`` output.

Design notes
------------

- The doc string for each page is the parser's ``description`` field, so
  the module docstring stays where it belongs (in the module).
- We invoke ``parse_args(['--help'])`` and catch the ``SystemExit`` argparse
  raises after printing help. Stdout is captured so nothing leaks. This
  is more robust than reaching into ``parser._actions`` since it's what
  the user actually sees when they type ``dvbfixer X --help``.
- Heavy scientific imports (OpenMM, Modeller, PDBFixer, MDAnalysis) are
  loaded lazily by the subcommand modules — this script's cost is
  dominated by their side-effectful top-of-module imports. Keeping the
  script single-purpose so CI can run it in the fast lane.
"""

from __future__ import annotations

import argparse
import contextlib
import importlib
import io
import sys
from pathlib import Path

from dvbfixer.command_registry import COMMAND_REGISTRY

REPO_ROOT = Path(__file__).resolve().parent.parent
REFERENCE_DIR = REPO_ROOT / "docs" / "reference"

# One entry per subcommand exposed by ``dvbfixer --help``. Names match the
# CLI command; module path is what ``dvbfixer.cli`` imports for that
# command. Order matches ``dvbfixer.cli.COMMANDS`` so the index page
# reads left-to-right the way users see it.
COMMANDS: list[tuple[str, str]] = [
    (command.name, command.module) for command in COMMAND_REGISTRY
]


def _capture_help(module_path: str) -> str:
    """Import ``module_path``, invoke its ``parse_args(['--help'])``, return
    the captured stdout.

    argparse prints help and calls ``sys.exit(0)``. We catch the
    ``SystemExit`` so the script can move on to the next command.
    """
    mod = importlib.import_module(module_path)
    parse_args = getattr(mod, "parse_args", None)
    if parse_args is None:
        raise RuntimeError(f"{module_path} has no parse_args()")
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf), contextlib.suppress(SystemExit):
        parse_args(["--help"])
    return buf.getvalue()


def _render_page(cmd: str, help_text: str) -> str:
    """Wrap the captured ``--help`` in a Markdown page.

    Kept minimal on purpose — this file is generated, so the more we put
    in it the more drift risk we take on. Prose that talks *about* the
    command lives in ``docs/commands/{cmd}.md``; this file only holds
    the exact flag surface.
    """
    return (
        f"# `dvbfixer {cmd}` — CLI reference\n\n"
        f"> This page is generated by `scripts/gen_cli_reference.py` from\n"
        f"> the subcommand's `parse_args()`. Do not edit by hand.\n"
        f"> For prose about how to use `{cmd}`, see "
        f"[`docs/commands/{cmd}.md`](../commands/{cmd}.md).\n\n"
        f"```\n{help_text.rstrip()}\n```\n"
    )


def _render_index() -> str:
    lines = [
        "# CLI reference",
        "",
        "> Auto-generated from each subcommand's `parse_args()` by",
        "> `scripts/gen_cli_reference.py`. Runs in CI (via `--check`) so",
        "> the pages here always match the code. Do not edit by hand.",
        "",
        "| Command | Reference |",
        "|---|---|",
    ]
    for cmd, _ in COMMANDS:
        lines.append(f"| `dvbfixer {cmd}` | [`{cmd}.md`]({cmd}.md) |")
    lines.append("")
    return "\n".join(lines)


def _gather() -> dict[Path, str]:
    """Build the full reference tree in memory.

    Returns a mapping from destination path (relative to REFERENCE_DIR)
    to file content. Used by both write and --check modes.
    """
    pages: dict[Path, str] = {}
    for cmd, module_path in COMMANDS:
        try:
            help_text = _capture_help(module_path)
        except Exception as exc:  # noqa: BLE001 — surface any subcommand issue
            print(f"ERROR: {cmd} ({module_path}): {exc}", file=sys.stderr)
            raise
        pages[REFERENCE_DIR / f"{cmd}.md"] = _render_page(cmd, help_text)
    pages[REFERENCE_DIR / "index.md"] = _render_index()
    return pages


def _read_existing(path: Path) -> str | None:
    try:
        return path.read_text()
    except FileNotFoundError:
        return None


def _cmd_write(pages: dict[Path, str]) -> int:
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for path, content in pages.items():
        existing = _read_existing(path)
        if existing == content:
            continue
        path.write_text(content)
        written += 1
        print(f"  wrote {path.relative_to(REPO_ROOT)}")
    if written == 0:
        print("CLI reference already up to date.")
    else:
        print(f"Updated {written} reference file(s).")
    return 0


def _cmd_check(pages: dict[Path, str]) -> int:
    drifted: list[str] = []
    missing: list[str] = []
    for path, content in pages.items():
        existing = _read_existing(path)
        rel = str(path.relative_to(REPO_ROOT))
        if existing is None:
            missing.append(rel)
        elif existing != content:
            drifted.append(rel)
    if not drifted and not missing:
        print("CLI reference is in sync with the code.")
        return 0
    print("CLI reference drift detected. Run:", file=sys.stderr)
    print("  python scripts/gen_cli_reference.py", file=sys.stderr)
    print("", file=sys.stderr)
    if missing:
        print("Missing files:", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
    if drifted:
        print("Drifted files:", file=sys.stderr)
        for d in drifted:
            print(f"  {d}", file=sys.stderr)
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_cli_reference",
        description="Generate docs/reference/{cmd}.md from each subcommand's argparse.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; diff against committed tree, exit 1 on drift.",
    )
    args = parser.parse_args(argv)
    pages = _gather()
    return _cmd_check(pages) if args.check else _cmd_write(pages)


if __name__ == "__main__":
    raise SystemExit(main())
